### ISSUE TITLE
1.1.3 -> 1.1.4 throws 500 error - PHP 7.4.10 not supported for match()

### ISSUE THREAD

**Issue by Rvice** [MightyMCoder/InventoryManager#81]
**Describe the bug**
Upgraded from 1.0.7 by deleting the folder and putting in 1.1.7 the result of going to the plug now gives an Internal Server Error

**To Reproduce**
1. Have 1.0.7 configured and running
2. Delete the plugin folder
3. Upload 1.1.7 into the plugin folder
4. Access the plugin and see the Internal Server Error

**Expected behavior**
Expect the plugin to work properly

**Screenshots**
Internal Server Error
The server encountered an internal error or misconfiguration and was unable to complete your request.

Please contact the server administrator, and inform them of the time the error occurred, and anything you might have done that may have caused the error.

More information about this error may be available in the server error log.

** Additional information **
1.0.7 -> 1.1.0 works
1.1.0 -> 1.1.1 works
1.1.1 -> 1.1.2 works
1.1.2 -> 1.1.3 works
1.1.3 -> 1.1.4 Gives internal server error
1.0.7 -> 1.1.7 Gives internal server error <-- Original Problem

**Comment by MightyMCoder** [comment]
Hi @Rvice,
do you have a backup/export of your data? If not, please backup your Database, a least all \*\_inventory_manager\_\* tables.

I think the problem comes from the \*\_plugin_preferences table. Can you provide me an export of this table?

**Comment by Rvice** [comment]
Note, my "items" in the inventory contain characters ' and "
Could it be related to that?

[adm_plugin_preferences.sql](https://github.com/user-attachments/files/20373308/adm_plugin_preferences.txt)

**Comment by Rvice** [comment]
Note, my "items" in the inventory contain characters ' and "
~~Could it be related to that?~~ It is not related to these, I changed " to inch and ' to ft and the same issue

[adm_plugin_preferences.sql](https://github.com/user-attachments/files/20373477/adm_plugin_preferences.txt)

**Comment by MightyMCoder** [comment]
i tried to reproduce your problem with your current plugin preferences and some test items containing the characters ' and " but i cannot reproduce your internal server error...

It could be possible that some of your item_fields got messed up when updating. That was finally fixed in v1.1.6.
But this is just guessing....

Please try to update to v1.1.4 or later again and sent me relevant parts from your log file. You could also enter the "Inspector" / "developer" browser tool and have a look if an error message is displayed there.

**Comment by Rvice** [comment]
Going back to 1.1.3 everything works fine, everything after fails (through 1.1.7)

Inspector gives error: Failed to load resource: the server responded with a status of 500 (Internal Server Error)

In accessing a different page (the Change Item) i get the following in the header
```Notice: Undefined index: disable_borrowing in .../adm_plugins/inventory_manager/items/items_edit_new.php on line 82

Warning: Cannot modify header information - headers already sent by (output started at .../adm_plugins/inventory_manager/items/items_edit_new.php:82) in .../adm_program/system/classes/HtmlPage.php on line 432```

**Comment by Rvice** [comment]
Additionally, I "Uninstalled" on all organizations in version 1.1.3 and 1.1.4-1.1.7 still doesn't work

**Comment by MightyMCoder** [comment]
Ok have you tried to delete your website data and cache? This behaviour is a bit strange.

I would clear the website data and cache and then try to enter the InventoryManager again but not via the menu-link. Try to directly call the URL **{YOUR_URL_BASE}/adm_plugins/inventory_manager/inventory_manager.php**

**Comment by Rvice** [comment]
Same behavior direct to the URL and deleting the website data and cache

**Comment by MightyMCoder** [comment]
I think I need your log file. I don't know what exactly is going wrong here. 

You can also sent me the data via [mail](mailto:matze199730@gmail.com) if you don't want to post it here.

**Comment by Rvice** [comment]
I sent my admidio file via email.

**Comment by Rvice** [comment]
I've narrowed down the error, not that I can get the reason why
```php
    case 'xlsx':
        //$contentType = match ($getMode) {
        //    'csv' => 'text/csv; charset=' . $charset,
        //    'xlsx' => 'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet',
        //    'ods' => 'application/vnd.oasis.opendocument.spreadsheet',
        //    default => throw new InvalidArgumentException('Invalid mode'),
        //};

        //$writerClass = match ($getMode) {
        //    'csv' => Csv::class,
        //    'xlsx' => Xlsx::class,
        //    'ods' => Ods::class,
        //    default => throw new InvalidArgumentException('Invalid mode'),
        //};

        header('Content-disposition: attachment; filename="' . $filename . '"');
        //header("Content-Type: $contentType");
        header('Content-Transfer-Encoding: binary');
        header('Cache-Control: must-revalidate');
        header('Pragma: public');

        $spreadsheet = new Spreadsheet();
        $spreadsheet->getProperties()
            ->setCreator($gCurrentUser->getValue('FIRST_NAME') . ' ' . $gCurrentUser->getValue('LAST_NAME'))
            ->setTitle($filename)
            ->setSubject($gL10n->get('PLG_INVENTORY_MANAGER_ITEMLIST'))
            ->setCompany($gCurrentOrganization->getValue('org_longname'))
            ->setKeywords($gL10n->get('PLG_INVENTORY_MANAGER_NAME_OF_PLUGIN') . ', ' . $gL10n->get('PLG_INVENTORY_MANAGER_ITEM'))
            ->setDescription($gL10n->get('PLG_INVENTORY_MANAGER_CREATED_WITH'));

        $sheet = $spreadsheet->getActiveSheet();
        $sheet->fromArray(array_keys($header), NULL, 'A1');
        $sheet->fromArray($rows, NULL, 'A2');

        if (!$getMode == 'csv') {
            foreach ($strikethroughs as $index => $strikethrough) {
                if ($strikethrough) {
                    $sheet->getStyle('A' . ($index + 2) . ':' . $sheet->getHighestColumn() . ($index + 2))
                        ->getFont()->setStrikethrough(true);
                }
            }

            formatSpreadsheet($spreadsheet, $rows, true);
        }

        //$writer = new $writerClass($spreadsheet);
        $writer->save('php://output');
        break;
```

Commenting out the lines above stop it from crashing

**Comment by Rvice** [comment]
Further testing, `match()` is what's failing

Even these lines crash
```php
    case 'xlsx':
		$food = 'cake';

		$contentType = match ($food) {
			'apple' => 'This food is an apple',
			'bar' => 'This food is a bar',
			'cake' => 'This food is a cake',
		};
```

**Comment by Rvice** [comment]
Is this because match is part of PHP 8? my server is PHP 7.4.10

**Comment by MightyMCoder** [comment]
ok this makes sense. i forgot o ask you about your PHP version... sorry for that...

**Comment by MightyMCoder** [comment]
fast fix for you:

just replace 
```php
        $contentType = match ($getMode) {
            'csv' => 'text/csv; charset=' . $charset,
            'xlsx' => 'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet',
            'ods' => 'application/vnd.oasis.opendocument.spreadsheet',
            default => throw new InvalidArgumentException('Invalid mode'),
        };

        $writerClass = match ($getMode) {
            'csv' => Csv::class,
            'xlsx' => Xlsx::class,
            'ods' => Ods::class,
            default => throw new InvalidArgumentException('Invalid mode'),
        };
```
with this:
```php
        $contentTypes = array(
            'csv'  => 'text/csv; charset=' . $charset,
            'xlsx' => 'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet',
            'ods'  => 'application/vnd.oasis.opendocument.spreadsheet',
        );

        $writerClasses = array(
            'csv'  => Csv::class,
            'xlsx' => Xlsx::class,
            'ods'  => Ods::class,
        );

        if (!isset($contentTypes[$getMode], $writerClasses[$getMode])) {
            throw new InvalidArgumentException('Invalid mode');
        }

        $contentType = $contentTypes[$getMode];
        $writerClass = $writerClasses[$getMode];
```

sorry that it took so long to find the problem...

**Comment by Rvice** [comment]
That works, also added a translation in the PR
